"""initial

Revision ID: c6bb5b6b965a
Revises:
Create Date: 2026-05-05 18:57:04.869066

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6bb5b6b965a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_source'), 'analytics_events', ['source'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('pending_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_key', sa.String(length=20), nullable=False),
    sa.Column('amount_value', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'payment_id', name='uq_pending_payments_provider_payment')
    )
    op.create_index(op.f('ix_pending_payments_payment_id'), 'pending_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_pending_payments_provider'), 'pending_payments', ['provider'], unique=False)
    op.create_index(op.f('ix_pending_payments_status'), 'pending_payments', ['status'], unique=False)
    op.create_index(op.f('ix_pending_payments_user_id'), 'pending_payments', ['user_id'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('photo_file_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_table('processed_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_key', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'payment_id', name='uq_processed_payments_provider_payment')
    )
    op.create_index(op.f('ix_processed_payments_payment_id'), 'processed_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_processed_payments_provider'), 'processed_payments', ['provider'], unique=False)
    op.create_index(op.f('ix_processed_payments_user_id'), 'processed_payments', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_until', sa.DateTime(), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('ai_requests_today', sa.Integer(), nullable=False),
    sa.Column('last_request_date', sa.Date(), nullable=True),
    sa.Column('weather_notify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=200), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('file_id', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('portion', sa.String(length=100), nullable=False),
    sa.Column('portion_grams', sa.Float(), nullable=True),
    sa.Column('meal_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('repeat', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_done', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vet_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(length=200), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notes_user_id'), 'voice_notes', ['user_id'], unique=False)
    op.create_table('water_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_records')
    op.drop_table('water_entries')
    op.drop_index(op.f('ix_voice_notes_user_id'), table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_table('vet_visits')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('food_entries')
    op.drop_table('documents')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_processed_payments_user_id'), table_name='processed_payments')
    op.drop_index(op.f('ix_processed_payments_provider'), table_name='processed_payments')
    op.drop_index(op.f('ix_processed_payments_payment_id'), table_name='processed_payments')
    op.drop_table('processed_payments')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_pending_payments_user_id'), table_name='pending_payments')
    op.drop_index(op.f('ix_pending_payments_status'), table_name='pending_payments')
    op.drop_index(op.f('ix_pending_payments_provider'), table_name='pending_payments')
    op.drop_index(op.f('ix_pending_payments_payment_id'), table_name='pending_payments')
    op.drop_table('pending_payments')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_source'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
